import type { Metadata } from "next";
import { primaryFont, secondaryFont } from "@/lib/fonts"; 
import "./globals.css";

export const metadata: Metadata = {
  title: "Challenger Class - SHT 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
